export const Font = {
  // All WorkSans
  Work100: 'WorkSans-Thin',
  Work100Italic: 'WorkSans-ThinItalic',
  Work200: 'WorkSans-ExtraLight',
  Work200Italic: 'WorkSans-ExtraLightItalic',
  Work300: 'WorkSans-Light',
  Work300Italic: 'WorkSans-LightItalic',
  Work400: 'WorkSans-Regular',
  Work400Italic: 'WorkSans-Italic',
  Work500: 'WorkSans-Medium',
  Work500Italic: 'WorkSans-MediumItalic',
  Work600: 'WorkSans-SemiBold',
  Work600Italic: 'WorkSans-SemiBoldItalic',
  Work700: 'WorkSans-Bold',
  Work700Italic: 'WorkSans-BoldItalic',
  Work800: 'WorkSans-ExtraBold',
  Work800Italic: 'WorkSans-ExtraBoldItalic',
  Work900: 'WorkSans-Black',
  Work900Italic: 'WorkSans-BlackItalic',
  InterItalic: 'Inter-Italic',
};
